[2022-04-12 12:55:32,093] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: openDataETL.extract manual__2022-04-12T12:55:27.121131+00:00 [queued]>
[2022-04-12 12:55:32,135] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: openDataETL.extract manual__2022-04-12T12:55:27.121131+00:00 [queued]>
[2022-04-12 12:55:32,136] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-12 12:55:32,137] {taskinstance.py:1250} INFO - Starting attempt 1 of 3
[2022-04-12 12:55:32,139] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-12 12:55:32,182] {taskinstance.py:1270} INFO - Executing <Task(PythonOperator): extract> on 2022-04-12 12:55:27.121131+00:00
[2022-04-12 12:55:32,192] {standard_task_runner.py:52} INFO - Started process 738 to run task
[2022-04-12 12:55:32,201] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'openDataETL', 'extract', 'manual__2022-04-12T12:55:27.121131+00:00', '--job-id', '76', '--raw', '--subdir', 'DAGS_FOLDER/openDataETL.py', '--cfg-path', '/tmp/tmpfl5jqyvz', '--error-file', '/tmp/tmpi9sl8915']
[2022-04-12 12:55:32,205] {standard_task_runner.py:80} INFO - Job 76: Subtask extract
[2022-04-12 12:55:32,353] {logging_mixin.py:109} INFO - Running <TaskInstance: openDataETL.extract manual__2022-04-12T12:55:27.121131+00:00 [running]> on host 474cd328f92b
[2022-04-12 12:55:32,527] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=openDataETL
AIRFLOW_CTX_TASK_ID=extract
AIRFLOW_CTX_EXECUTION_DATE=2022-04-12T12:55:27.121131+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-04-12T12:55:27.121131+00:00
[2022-04-12 12:59:01,896] {python.py:175} INFO - Done. Returned value was: None
[2022-04-12 12:59:02,066] {taskinstance.py:1288} INFO - Marking task as SUCCESS. dag_id=openDataETL, task_id=extract, execution_date=20220412T125527, start_date=20220412T125532, end_date=20220412T125902
[2022-04-12 12:59:02,286] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-12 12:59:02,552] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
