[2022-04-11 12:59:58,074] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: openDataETL.extract manual__2022-04-11T12:59:52.819057+00:00 [queued]>
[2022-04-11 12:59:58,135] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: openDataETL.extract manual__2022-04-11T12:59:52.819057+00:00 [queued]>
[2022-04-11 12:59:58,136] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-11 12:59:58,138] {taskinstance.py:1250} INFO - Starting attempt 1 of 3
[2022-04-11 12:59:58,140] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-11 12:59:58,200] {taskinstance.py:1270} INFO - Executing <Task(PythonOperator): extract> on 2022-04-11 12:59:52.819057+00:00
[2022-04-11 12:59:58,214] {standard_task_runner.py:52} INFO - Started process 1311 to run task
[2022-04-11 12:59:58,245] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'openDataETL', 'extract', 'manual__2022-04-11T12:59:52.819057+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/try.py', '--cfg-path', '/tmp/tmp2aji6ky8', '--error-file', '/tmp/tmpchda9tem']
[2022-04-11 12:59:58,248] {standard_task_runner.py:80} INFO - Job 18: Subtask extract
[2022-04-11 12:59:58,448] {logging_mixin.py:109} INFO - Running <TaskInstance: openDataETL.extract manual__2022-04-11T12:59:52.819057+00:00 [running]> on host 474cd328f92b
[2022-04-11 12:59:58,648] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=openDataETL
AIRFLOW_CTX_TASK_ID=extract
AIRFLOW_CTX_EXECUTION_DATE=2022-04-11T12:59:52.819057+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-04-11T12:59:52.819057+00:00
[2022-04-11 13:00:06,251] {logging_mixin.py:109} INFO - æœ‰
[2022-04-11 13:00:06,344] {python.py:175} INFO - Done. Returned value was: None
[2022-04-11 13:00:06,391] {taskinstance.py:1288} INFO - Marking task as SUCCESS. dag_id=openDataETL, task_id=extract, execution_date=20220411T125952, start_date=20220411T125958, end_date=20220411T130006
[2022-04-11 13:00:06,505] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-11 13:00:06,692] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
