[2022-04-11 12:22:49,228] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: openDataETL.transform manual__2022-04-11T12:22:31.003924+00:00 [queued]>
[2022-04-11 12:22:49,267] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: openDataETL.transform manual__2022-04-11T12:22:31.003924+00:00 [queued]>
[2022-04-11 12:22:49,269] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-11 12:22:49,270] {taskinstance.py:1250} INFO - Starting attempt 1 of 3
[2022-04-11 12:22:49,272] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-11 12:22:49,317] {taskinstance.py:1270} INFO - Executing <Task(PythonOperator): transform> on 2022-04-11 12:22:31.003924+00:00
[2022-04-11 12:22:49,327] {standard_task_runner.py:52} INFO - Started process 299 to run task
[2022-04-11 12:22:49,335] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'openDataETL', 'transform', 'manual__2022-04-11T12:22:31.003924+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/try.py', '--cfg-path', '/tmp/tmp8pn75dic', '--error-file', '/tmp/tmp_h6e6n62']
[2022-04-11 12:22:49,338] {standard_task_runner.py:80} INFO - Job 13: Subtask transform
[2022-04-11 12:22:49,464] {logging_mixin.py:109} INFO - Running <TaskInstance: openDataETL.transform manual__2022-04-11T12:22:31.003924+00:00 [running]> on host 474cd328f92b
[2022-04-11 12:22:49,592] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=openDataETL
AIRFLOW_CTX_TASK_ID=transform
AIRFLOW_CTX_EXECUTION_DATE=2022-04-11T12:22:31.003924+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-04-11T12:22:31.003924+00:00
[2022-04-11 12:22:49,640] {python.py:175} INFO - Done. Returned value was: None
[2022-04-11 12:22:49,673] {taskinstance.py:1288} INFO - Marking task as SUCCESS. dag_id=openDataETL, task_id=transform, execution_date=20220411T122231, start_date=20220411T122249, end_date=20220411T122249
[2022-04-11 12:22:49,755] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-11 12:22:49,851] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
