[2022-04-11 14:11:36,169] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: openDataETL.extract manual__2022-04-11T14:11:30.743562+00:00 [queued]>
[2022-04-11 14:11:36,225] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: openDataETL.extract manual__2022-04-11T14:11:30.743562+00:00 [queued]>
[2022-04-11 14:11:36,227] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-11 14:11:36,229] {taskinstance.py:1250} INFO - Starting attempt 1 of 3
[2022-04-11 14:11:36,231] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-11 14:11:36,290] {taskinstance.py:1270} INFO - Executing <Task(PythonOperator): extract> on 2022-04-11 14:11:30.743562+00:00
[2022-04-11 14:11:36,300] {standard_task_runner.py:52} INFO - Started process 5046 to run task
[2022-04-11 14:11:36,320] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'openDataETL', 'extract', 'manual__2022-04-11T14:11:30.743562+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/try.py', '--cfg-path', '/tmp/tmp6j6g3g__', '--error-file', '/tmp/tmp8plthl4_']
[2022-04-11 14:11:36,332] {standard_task_runner.py:80} INFO - Job 26: Subtask extract
[2022-04-11 14:11:36,512] {logging_mixin.py:109} INFO - Running <TaskInstance: openDataETL.extract manual__2022-04-11T14:11:30.743562+00:00 [running]> on host 474cd328f92b
[2022-04-11 14:11:36,761] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=openDataETL
AIRFLOW_CTX_TASK_ID=extract
AIRFLOW_CTX_EXECUTION_DATE=2022-04-11T14:11:30.743562+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-04-11T14:11:30.743562+00:00
[2022-04-11 14:11:37,890] {logging_mixin.py:109} INFO - /opt/***
[2022-04-11 14:11:37,894] {python.py:175} INFO - Done. Returned value was: None
[2022-04-11 14:11:37,943] {taskinstance.py:1288} INFO - Marking task as SUCCESS. dag_id=openDataETL, task_id=extract, execution_date=20220411T141130, start_date=20220411T141136, end_date=20220411T141137
[2022-04-11 14:11:38,041] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-11 14:11:38,170] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
